"""Shared test fixtures for API and helper tests."""

from __future__ import annotations

from dataclasses import replace
import io
import json
from pathlib import Path
import zipfile

from fastapi.testclient import TestClient
import pytest

from modules.api_service import create_app
from modules.settings import SETTINGS, ExperimentSettings


@pytest.fixture()
def test_settings(tmp_path: Path) -> ExperimentSettings:
    """Provide isolated runtime settings for local integration tests.

    Args:
        tmp_path: Pytest-managed temporary directory fixture.

    Returns:
        Isolated ``ExperimentSettings`` instance for tests.
    """
    return replace(
        SETTINGS,
        backend_name="test-local",
        mount_dir=tmp_path / "mnt-local",
        port=19080,
        benchmark_output_dir=tmp_path / "results",
    )


@pytest.fixture()
def client(test_settings: ExperimentSettings) -> TestClient:
    """Create a FastAPI test client backed by an isolated temp mount.

    Args:
        test_settings: Runtime settings fixture configured for tests.

    Returns:
        Yielded FastAPI ``TestClient`` instance.
    """
    app = create_app(test_settings)
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture()
def tenant_header() -> dict[str, str]:
    """Return default tenant header for endpoint calls.

    Args:
        None.

    Returns:
        Default tenant header dictionary.
    """
    return {"X-Tenant-ID": "tenant-a"}


@pytest.fixture()
def other_tenant_header() -> dict[str, str]:
    """Return an alternate tenant header for isolation checks.

    Args:
        None.

    Returns:
        Alternate tenant header dictionary.
    """
    return {"X-Tenant-ID": "tenant-b"}


def read_zip_entry_names(content: bytes) -> list[str]:
    """Return sorted zip entry names from binary response content.

    Args:
        content: Binary ZIP payload returned by download endpoints.

    Returns:
        Sorted list of ZIP entry names.
    """
    with zipfile.ZipFile(io.BytesIO(content), mode="r") as archive:
        return sorted(archive.namelist())


def read_zip_metadata(content: bytes) -> dict[str, object]:
    """Read metadata JSON generated by download endpoint zip responses.

    Args:
        content: Binary ZIP payload returned by download endpoints.

    Returns:
        Parsed metadata dictionary from ``_metadata.json``.
    """
    with zipfile.ZipFile(io.BytesIO(content), mode="r") as archive:
        raw = archive.read("_metadata.json")
        return json.loads(raw.decode("utf-8"))
